name: test-workflow
run-name: test-workflow

on:
  workflow_dispatch:

jobs:
  print-tag:
    runs-on: ubuntu-latest

    steps:
      - name: prints test out
        run: echo Test

      - name: sleeps for 10 seconds
        run: sleep 10

      - name: prints test out
        run: echo Test
